---
title: "Agglomeration Graphs"
author: "Nikhil Kalathil"
date: "2024-03-03"
output: html_document
---


# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warnings = FALSE)
```

```{r, include = FALSE}
#Libraries
library(tigris)
library(tidyverse)
library(here)
library(leaflet)
library(ggrepel)
library(RColorBrewer)
library(grid)
library(gridExtra)
library(cowplot)
library(readxl)
library(janitor)
library(geofacet)
library(jsonlite)
library(ggridges)
library(sf)
library(here)
library(patchwork)
library(plotly)
library(leaflet.extras)
library(units)

set.seed(37)
title_theme <- theme(axis.text = element_text(size = 14), 
        axis.title = element_text(size = 18), 
        title = element_text(size = 20))

axis_theme <- theme(axis.text = element_text(size = 10), 
        axis.title = element_text(size = 18), 
         strip.text.x = element_text(size = 14))
```

```{r, include = FALSE}
#Area Crosswalks
area_codes <- readRDS(here("State Data/area_crosswalk.RDS")) %>% 
  mutate(area_title = str_remove(area_title, " -- Statewide")) %>% 
  mutate(area_fips = case_when(
    nchar(area_fips) == 4 ~ paste("0", area_fips, sep = ""), 
    TRUE ~ area_fips
  ))

states <- data.frame(state_abbr = state.abb, area_title = state.name)

area_codes <- left_join(area_codes, states) %>% 
  mutate(state_abbr = case_when(
    area_title == "District of Columbia" ~ "DC",
    area_title == "Puerto Rico" ~ "PR",
    TRUE ~ state_abbr))
```


```{r}
ExpandColorsLIGHT <- function(colors, n, steps = 11){
  if(n <= steps){
    suppressWarnings({
      sapply(colors, function(x){colorRampPalette(c(x, "#FFFFFF"))(steps)}) %>% 
        as.data.frame() %>% 
        filter(row_number() <= n) %>% 
        gather(key = original.color, value = expanded.color)
    })
  }else{
    warning("Select n < steps!")
  }
}
```


```{r}
ExpandColorsDARK <- function(colors, n, steps = 11){
  if(n <= steps){
    suppressWarnings({
      sapply(colors, function(x){colorRampPalette(c(x, "#000000"))(steps)}) %>% 
        as.data.frame() %>% 
        filter(row_number() <= n) %>% 
        gather(key = original.color, value = expanded.color)
    })
  }else{
    warning("Select n < steps!")
  }
}
```

```{r, include = FALSE}
#Map Data
county_sf <- counties(cb = TRUE) %>% 
  shift_geometry(position = "outside")
states_sf <- states(cb = TRUE, resolution = "20m") %>%
  shift_geometry(position = "outside")
```

```{r, include = FALSE}
#Change projection of data for leaflet

states_leaflet <- states_sf %>% 
  sf::st_transform('+proj=longlat +datum=WGS84')

counties_leaflet <- county_sf %>% 
  sf::st_transform('+proj=longlat +datum=WGS84') 
```

```{r, include = FALSE}
#Convert county data to a table
county_data <- counties_leaflet %>% 
  as_tibble() %>% 
  select(STATEFP, COUNTYFP, AFFGEOID) %>% 
  mutate(area_fips = paste(STATEFP, COUNTYFP, sep = ""), 
         st = as.numeric(STATEFP))
```


```{r, include = FALSE}
#Get center of each county
county_centers <- counties_leaflet %>% 
  filter(str_detect(NAME, "Mariana", negate = TRUE)) %>% 
  st_centroid() %>% 
  sf::st_transform('+proj=longlat +datum=WGS84')
```

```{r, include = FALSE}
#Load Existing Data
qcew_3digits <- readRDS(here("State Data/qcew_3digit.RDS")) %>% 
  mutate(industry_desc = substring(industry_title, 11))
```

```{r, include = FALSE}
#Simplify to get industry codes
ind_3digit <- qcew_3digits %>% 
  select(naics_3digit = ind_code, naics_3digit_label = industry_desc) %>% 
  distinct() %>% 
  arrange(naics_3digit_label)
```

```{r, include = FALSE}
#Define colors 
emp_ind_vector <- c(brewer.pal(9, "Greys")[4], "#cf4633", "#BEAED4", "#FDC086", "#FDBF6F",  "#386CB0", "#FB8072", brewer.pal(9, "Greys")[3], brewer.pal(9, "Greys")[8], "#80B1D3", "#F0027F",  "#4DAF4A", "#F1E2CC", "#6A3D9A", "#E78AC3", "#CBD5E8", "#666666", brewer.pal(9, "Greys")[5],  brewer.pal(9, "Greys")[6], "#A65628", brewer.pal(9, "Greys")[7])
```

```{r}
#create data frame mapping colors to industries
col_map <- data.frame(ind_3digit$naics_3digit_label, emp_ind_vector)
```

```{r}
rd_col <- data.frame(ind_3digit.naics_3digit_label = "Scientific R&D", emp_ind_vector = "#8DD3C7")
```

```{r}
col_map <- bind_rows(col_map, rd_col)
```


```{r}
# Map 3-digit NAICS to 3-digit Colors
get_col_vec <- function(data){ 
  data %>% 
    select(naics_3digit_label) %>% 
    distinct() %>% 
    unlist()
  }
```

```{r}
#Function to get appropriate 3-digit colors
get_col_match <- function(data){ 
  
 col_vec <- get_col_vec(data)
 
 col_out <- col_map %>% 
   filter(ind_3digit.naics_3digit_label %in% col_vec) %>% 
   select(emp_ind_vector) %>% 
   unlist() %>% 
   unname()
 
  return(col_out)
  
}
```

```{r}
#Get County GEOIDS and crosswalks
cbp_geoid <- read.csv(here("County Data/5_digit_naics_2019.csv")) %>% 
  mutate(area_fips = str_sub(GEO_ID, -5)) %>% 
  select(GEO_ID, NAME, area_fips) %>% distinct()

cbp_empzes <- read.csv(here("County Data/5_digit_naics_2019.csv")) %>% 
  select(EMPSZES_LABEL, EMPSZES) %>% 
  distinct()

cbp_io <- readRDS(here("Input Output Data/cbp_manf_IO_crosswalk.RDS")) 
```


```{r, include = FALSE}
#read county-level manufacturing data
cbp_2019 <- read.csv(here("County Data/6_digit_naics_CBP.csv")) %>% 
  left_join(cbp_geoid) %>% 
  left_join(county_data) %>% 
  left_join(area_codes %>% select(st, state_abbr)) %>% 
  mutate(across(.cols = c(EMP, ESTAB), ~ gsub(",", "", .)),
    emp_num = as.numeric(EMP), 
    ESTAB = as.numeric(ESTAB)) %>% 
  filter(str_detect(NAME, "Mariana", negate = TRUE)) %>% 
  left_join(cbp_empzes)
```


```{r}
cbp_2019_all <- read.csv(here("County Data/total_naics_2019.csv")) %>% 
  mutate(across(.cols = c(EMP, ESTAB), ~ gsub(",", "", .)),
    tot_emp = as.numeric(EMP), 
    tot_estab = as.numeric(ESTAB)) %>% 
  filter(str_detect(NAME, "Mariana", negate = TRUE), EMPSZES_LABEL == "All establishments") %>% 
  mutate(geo_merge = NAME) %>% 
  left_join(counties_leaflet %>% 
              mutate(geo_merge = paste(NAMELSAD, STATE_NAME, sep = ", ")) %>% 
              rename(county_name = NAME))
```



```{r}
#read Input Output Data
use_table_final <- readRDS(here("Input Output Data/use_table_final.RDS"))
sup_com_agg <- readRDS(here("Input Output Data/sup_com_agg.RDS"))
ind_agg <- readRDS(here("Input Output Data/ind_agg.RDS"))
com_agg <- readRDS(here("Input Output Data/com_agg.RDS"))
supply_table_final <- readRDS(here("Input Output Data/supply_table_final.RDS"))
```

```{r}
ind_crosswalk <- readRDS(here("Input Output Data/ind_crosswalk.RDS"))
```



```{r}
#Read NAICS Codes
naics_codes <- read.csv(here("NAICS/naics_codes.csv")) %>% 
  select(c(2,3))

colnames(naics_codes) <- c("industry_code", "industry_desc")
```

```{r, include = FALSE}
naics_2 <- naics_codes %>% 
  filter(str_length(industry_code) == 2 | industry_code == "31-33") %>% 
  mutate(industry_code = case_when(
    industry_code == "31-33" ~ 31.33, 
    TRUE ~ as.numeric(industry_code)
  ))
```

```{r}
naics_sub <- function(var, num){
   as.numeric(str_sub({{ var }}, 1, num))
}
```

# Results 

```{r}
final_cbp_results <- readRDS(here("Final Data/final_cbp_io_results_hhi.RDS"))
```


```{r}
state_quads <- readRDS(here("State Data/state_quadrants_1.RDS"))
```


```{r}
final_results_merge <- final_cbp_results %>% 
  filter(!is.na(state_abbr)) %>% 
  left_join(ind_crosswalk %>% rename(ind_code = industry_code)) %>% 
  left_join(state_quads %>% select(state_abbr, state_quadrant)) 
```


```{r}
filter_function <- function(data, var){
  
  data %>% 
    filter({{ var }} > 0) %>% 
    mutate(mean_var = mean(log({{ var} }), na.rm = TRUE)) %>% 
    select(mean_var) %>% 
    distinct() %>% 
    unlist() %>% 
    unname()
  
}
```

```{r}
agg_means <- data.frame(input_emp = filter_function(final_results_merge, input_emp), 
                        input_estabs = filter_function(final_results_merge, input_estabs), 
                        output_emp = filter_function(final_results_merge, output_emp), 
                        output_estabs = filter_function(final_results_merge, output_estabs), 
                        supply_emp = filter_function(final_results_merge, supply_emp), 
                        supply_estabs = filter_function(final_results_merge, supply_estabs))
```



### Employment and Establishments


```{r}
emp_emp <- final_results_merge %>% 
  filter(output_emp > 0, supply_emp != 0, state_abbr == "LA") %>% 
  ggplot() + 
  geom_point(shape = 21, aes(x = log(output_emp), y = log(supply_emp), fill = naics_3digit_label)) + 
  geom_hline(yintercept = agg_means$supply_emp) + 
  geom_vline(xintercept = agg_means$output_emp) + 
  scale_fill_manual(values = emp_ind_vector) + 
  guides(fill = "none") +
  facet_wrap(~naics_3digit_label) + 
  labs(x = "County-Subsector Index of Output Horizontal Agglomeration \nEmployment", y = "County-Subsector Index of Supply Vertical Agglomeration \nEmployment") +
  theme_bw() + 
  axis_theme

emp_emp
```

```{r}
emp_estabs <- final_results_merge %>% 
  filter(output_emp > 0, supply_estabs != 0, state_abbr == "LA") %>% 
  ggplot() + 
  geom_point(shape = 21, aes(x = log(output_emp), y = log(supply_estabs), fill = naics_3digit_label)) + 
  geom_hline(yintercept = agg_means$supply_estabs) + 
  geom_vline(xintercept = agg_means$output_emp) + 
  scale_fill_manual(values = emp_ind_vector) + 
  guides(fill = "none") +
  facet_wrap(~naics_3digit_label) + 
  labs(x = "County-Subsector Index of Output Horizontal Agglomeration \nEmployment", y = "County-Subsector Index of Supply Vertical Agglomeration \nEstablishments") +
  theme_bw() + 
  axis_theme

emp_estabs
```

```{r}
estabs_estabs <- final_results_merge %>% 
  filter(output_estabs > 0, supply_estabs != 0) %>% 
  ggplot() + 
  geom_point(shape = 21, aes(x = log(output_estabs), y = log(supply_estabs), fill = naics_3digit_label)) + 
  geom_hline(yintercept = agg_means$supply_estabs) + 
  geom_vline(xintercept = agg_means$output_estabs) + 
  scale_fill_manual(values = emp_ind_vector) + 
  guides(fill = "none") +
  facet_wrap(~naics_3digit_label) + 
  labs(x = "County-Subsector Index of Output Horizontal Agglomeration \nEstablishments", y = "County-Subsector Index of Supply Vertical Agglomeration \nEstablishments") +
  theme_bw() + 
  axis_theme

estabs_estabs
```


We can create a function to compare different types of agglomeration. 

```{r}
estabs_estabs_fn <- function(data, state_list){
  
  df <- data %>% 
    filter(output_estabs > 0, supply_estabs != 0, state_abbr %in% state_list)
  
  col_vec <- get_col_match(df)
  
  df %>% 
    ggplot() + 
    geom_point(shape = 21, aes(x = log(output_estabs), y = log(supply_estabs), fill = naics_3digit_label)) + 
    geom_vline(xintercept = agg_means$output_estabs) + 
    geom_hline(yintercept = agg_means$supply_estabs) + 
    scale_fill_manual(values = col_vec) + 
    guides(fill = "none") +
    labs(x = "County-Subsector Index of Output Horizontal Agglomeration \nEstablishments", y = "County-Subsector Index of Supply Vertical Agglomeration \nEstablishments") +
    theme_bw() + 
    axis_theme
}
```


```{r}
la_agg <- final_results_merge %>% 
  estabs_estabs_fn("LA")
```


```{r}
input_output_comp <- final_results_merge %>% 
  ggplot() + 
  geom_point(shape = 21, aes(x = log(output_estabs), y = log(input_estabs), fill = naics_3digit_label), alpha = 0.7) + 
  scale_fill_manual(values = emp_ind_vector) + 
  guides(fill = "none") +
  labs(x = "County-Subsector Index of Output Horizontal Agglomeration \nEstablishments", y = "County-Subsector Index of Input Horizontal Agglomeration \nEstablishments") +
  theme_bw() + 
  axis_theme

input_output_comp
```


```{r}
output_supply_comp <- final_results_merge %>% 
  filter(output_estabs > 0, supply_estabs != 0) %>% 
  ggplot() + 
  geom_point(shape = 21, aes(x = log(output_estabs), y = log(supply_estabs), fill = naics_3digit_label)) + 
  geom_vline(xintercept = agg_means$output_estabs) + 
  geom_hline(yintercept = agg_means$supply_estabs) + 
  scale_fill_manual(values = emp_ind_vector) + 
  guides(fill = "none") +
  labs(x = "County-Subsector Index of Output Horizontal Agglomeration \nEstablishments", y = "County-Subsector Index of Supply Vertical Agglomeration \nEstablishments") +
  theme_bw() + 
  axis_theme

output_supply_comp
```

```{r}
input_supply_comp <- final_results_merge %>% 
  ggplot() + 
  geom_point(shape = 21, aes(x = log(input_estabs), y = log(supply_estabs), fill = naics_3digit_label), alpha = 0.7) + 
  scale_fill_manual(values = emp_ind_vector) + 
  guides(fill = "none") +
  labs(x = "County-Subsector Index of Input Horizontal Agglomeration \nEstablishments", y = "County-Subsector Index of Supply Vertical Agglomeration \nEstablishments") +
  theme_bw() + 
  axis_theme

input_supply_comp
```

```{r}
sector_comp <- final_results_merge %>% 
  filter(naics_3digit %in% c(334, 336))

sector_col <- get_col_match(sector_comp)

sector_comp1 <- sector_comp %>% 
  ggplot() + 
  geom_point(shape = 21, aes(x = log(output_estabs), y = log(supply_estabs), fill = naics_3digit_label)) + 
  geom_vline(xintercept = -10) + 
  geom_hline(yintercept = -16) + 
  scale_fill_manual(values = sector_col) + 
  facet_wrap(~naics_3digit_label) + 
  guides(fill = "none") +
  labs(x = "County-Subsector Index of Output Horizontal Agglomeration \nEstablishments", y = "County-Subsector Index of Supply Vertical Agglomeration \nEstablishments") +
  theme_bw() + 
  axis_theme

sector_comp1
```

```{r}
sector_comp <- final_results_merge %>% 
  filter(naics_3digit %in% c(336)) %>% 
  group_by(industry_desc) %>% 
  mutate(count = n()) %>% 
  filter(count > 3)

sector_col <- get_col_match(sector_comp)

sector_comp2 <- sector_comp %>% 
  filter(output_estabs > 0, supply_estabs != 0) %>% 
  ggplot() + 
  geom_point(shape = 21, aes(x = log(output_estabs), y = log(supply_estabs), fill = naics_3digit_label)) + 
  geom_vline(xintercept = agg_means$output_estabs) + 
  geom_hline(yintercept = agg_means$supply_estabs) + 
  scale_fill_manual(values = sector_col) + 
  facet_wrap(~industry_desc) + 
  guides(fill = "none") +
  labs(x = "County-Subsector Index of Output Horizontal Agglomeration \nEstablishments", y = "County-Subsector Index of Supply Vertical Agglomeration \nEstablishments") +
  theme_bw() + 
  axis_theme

sector_comp2
```


```{r}
sector_comp_gran <- final_results_merge %>% 
  filter(industry_code %in% c("334413", "336411", "336111"))

sector_gran_col <- get_col_match(sector_comp_gran)
```

```{r}
gran_graph_estabs_estabs <- sector_comp_gran %>%
  filter(output_estabs > 0, supply_estabs != 0) %>% 
  mutate(county_label = case_when(state_abbr == "CA" ~ NAME)) %>% 
  ggplot(aes(text = NAME)) + 
  geom_point(shape = 21, aes(x = log(output_estabs), y = log(supply_estabs), fill = naics_3digit_label), size = 3) + 
  # geom_label_repel(aes(x = log(output_estabs), y = log(supply_estabs), fill = naics_3digit_label, label = county_label)) + 
  scale_fill_manual(values = sector_gran_col) + 
  geom_vline(xintercept = agg_means$output_estabs) + 
  geom_hline(yintercept = agg_means$supply_estabs) + 
  facet_wrap(~industry_desc) + 
  guides(fill = "none") +
  labs(x = "County-Subsector Index of Output Horizontal Agglomeration \nEstablishments", y = "County-Subsector Index of Supply Vertical Agglomeration \nEstablishments") +
  theme_bw() + 
  axis_theme
```

```{r}
semicondcutor_comp <- final_results_merge %>% 
  filter(industry_code %in% c("334413"))

semicondcutor_comp_col <- get_col_match(semicondcutor_comp)
```

```{r}
semiconductor_estabs_estabs <- semicondcutor_comp %>%
  filter(output_estabs > 0, supply_estabs != 0) %>% 
  mutate(`Horizontal Agglomeration` = log(output_estabs), `Vertical Agglomeration` = log(supply_estabs), `3 Digit Naics` = naics_3digit_label, `Industry Location Quotient` = NAICS_emp_lq*10) %>% 
  ggplot(aes(text = NAME)) + 
    geom_vline(xintercept = semicondcutor_comp %>% filter_function(output_estabs), color = semicondcutor_comp_col, size = 2) + 
    geom_hline(yintercept = semicondcutor_comp %>% filter_function(supply_estabs), color = semicondcutor_comp_col, size = 2) + 
  geom_point(shape = 21, aes(x = `Horizontal Agglomeration`, y = `Vertical Agglomeration`, size = `Industry Location Quotient`), fill = "#FDC086") + 
  scale_fill_manual(values = semicondcutor_comp_col) + 
  geom_vline(xintercept = agg_means$output_estabs) + 
  geom_hline(yintercept = agg_means$supply_estabs) + 
  xlim(-15, -7.5) + 
  ylim(-25, -10) + 
  facet_wrap(~industry_desc) + 
  guides(fill = "none", size = "none") +
  labs(x = "County-Subsector Index of Output Horizontal Agglomeration \nEstablishments", y = "County-Subsector Index of Supply Vertical Agglomeration \nEstablishments") +
  theme_bw() + 
  axis_theme
```


```{r}
county_comp_estabs_estabs <- semiconductor_estabs_estabs + 
geom_vline(xintercept = semicondcutor_comp %>% filter_function(output_estabs), color = semicondcutor_comp_col, size = 2) + 
    geom_hline(yintercept = semicondcutor_comp %>% filter_function(supply_estabs), color = semicondcutor_comp_col, size = 2) + 
  geom_point(data = semicondcutor_comp %>% filter(str_detect(NAME, "Washington County|Dallas|Maricopa")), aes(x = log(output_estabs), y = log(supply_estabs), size = ind_emp_lq*10), shape = 21, fill = "light grey") + 
  geom_label_repel(data = semicondcutor_comp %>% filter(str_detect(NAME, "Washington County|Dallas|Maricopa")), aes(x = log(output_estabs), y = log(supply_estabs), label = NAME), fill = "light grey", size = 5) 
```


```{r}
semiconductor_estabs_emp <- semicondcutor_comp %>%
  filter(output_estabs > 0, supply_emp != 0) %>% 
  ggplot(aes(text = NAME)) + 
  geom_point(shape = 21, aes(x = log(output_estabs), y = log(supply_emp), fill = naics_3digit_label, size = ind_emp_lq*10)) + 
  scale_fill_manual(values = semicondcutor_comp_col) + 
  geom_vline(xintercept = agg_means$output_estabs) + 
  geom_hline(yintercept = agg_means$supply_emp) + 
  xlim(-15, -7.5) + 
  ylim(-25, -10) + 
  facet_wrap(~industry_desc) + 
  guides(fill = "none", size = "none") +
  labs(x = "County-Subsector Index of Output Horizontal Agglomeration \nEstablishments", y = "County-Subsector Index of Supply Vertical Agglomeration \nEmployment") +
  theme_bw() + 
  axis_theme
```

```{r}
county_comp_estabs_emp <- semiconductor_estabs_estabs + 
geom_vline(xintercept = semicondcutor_comp %>% filter_function(output_estabs), color = semicondcutor_comp_col, size = 2) + 
    geom_hline(yintercept = semicondcutor_comp %>% filter_function(supply_emp), color = semicondcutor_comp_col, size = 2) + 
  geom_point(data = semicondcutor_comp %>% filter(str_detect(NAME, "Washington County|Dallas|Maricopa")), aes(x = log(output_estabs), y = log(supply_emp), size = ind_emp_lq*10), shape = 21, fill = "light grey") + 
  geom_label_repel(data = semicondcutor_comp %>% filter(str_detect(NAME, "Washington County|Dallas|Maricopa")), aes(x = log(output_estabs), y = log(supply_emp), label = NAME), fill = "light grey", size = 5) 
```



```{r}
mask_states <- final_results_merge %>% 
  filter(state_abbr %in% c("MA", "AL", "IN", "NY", "MI", "WA")) %>% 
  filter(output_estabs > 0, supply_estabs != 0) 

mask_col <- get_col_match(mask_states)

geog_comp <- mask_states %>% 
  ggplot() + 
  geom_point(shape = 21, aes(x = log(output_estabs), y = log(supply_estabs), fill = naics_3digit_label)) + 
  geom_hline(yintercept = agg_means$supply_estabs) + 
  geom_vline(xintercept = agg_means$output_estabs) + 
  scale_fill_manual(values = mask_col) + 
  guides(fill = "none") +
  facet_wrap(~state_abbr) + 
  labs(x = "County-Subsector Index of Output Horizontal Agglomeration \nEstablishments", y = "County-Subsector Index of Supply Vertical Agglomeration \nEstablishments") +
  theme_bw() + 
  axis_theme
  
```


```{r}
gran_graph_estabs_emp <- sector_comp_gran %>%
  filter(output_estabs > 0, supply_emp != 0) %>% 
  ggplot() + 
  geom_point(shape = 21, aes(x = log(output_estabs), y = log(supply_emp), fill = naics_3digit_label)) + 
  scale_fill_manual(values = sector_gran_col) + 
  geom_vline(xintercept = agg_means$output_estabs) + 
  geom_hline(yintercept = agg_means$supply_emp) + 
  facet_wrap(~industry_desc) + 
  guides(fill = "none") +
  labs(x = "County-Subsector Index of Output Horizontal Agglomeration \nEstablishments", y = "County-Subsector Index of Supply Vertical Agglomeration \nEmployment") +
  theme_bw() + 
  axis_theme
```

